[[pages]]
path = "app.py"
name = "Sabores"

[[pages]]
path = "pages/venda.py"
name = "Vender"

[[pages]]
path = "pages/producao.py"
name = "Produzir"

[[pages]]
path = "pages/Análises.py"
name = "Análises"

